In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

In [4]:
s = Series([10,20,30], index=['a','b','c'])

In [5]:
s

a    10
b    20
c    30
dtype: int64

In [6]:
df = DataFrame(s, columns=['A'])
df

A
a  10
b  20
c  30

In [8]:
s.__class__

pandas.core.series.Series

In [9]:
df.__class__

pandas.core.frame.DataFrame

In [10]:
s.to_numpy()

array([10, 20, 30])

In [11]:
df.to_numpy()

array([[10],
       [20],
       [30]])

In [12]:
s.to_numpy().shape

(3,)

In [13]:
df.to_numpy().shape

(3, 1)

In [14]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [15]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [16]:
df.columns

Index(['A'], dtype='object')

In [24]:
d = {'one': Series([1, 2], index=['a', 'b']),
    'two': Series([1, 2, 3], index=['a', 'b', 'c'])}
d

{'one': a    1
 b    2
 dtype: int64,
 'two': a    1
 b    2
 c    3
 dtype: int64}

In [25]:
df = DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  NaN    3

In [31]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [32]:
df = DataFrame(x)
df.columns = ['A', 'B']
df.index = [11, 22]
df

A  B
11  0  1
22  2  3

In [33]:
import statsmodels.api as sm

In [35]:
trees = sm.datasets.get_rdataset('trees')['data']
trees

Girth  Height  Volume
0     8.3      70    10.3
1     8.6      65    10.3
2     8.8      63    10.2
3    10.5      72    16.4
4    10.7      81    18.8
5    10.8      83    19.7
6    11.0      66    15.6
7    11.0      75    18.2
8    11.1      80    22.6
9    11.2      75    19.9
10   11.3      79    24.2
11   11.4      76    21.0
12   11.4      76    21.4
13   11.7      69    21.3
14   12.0      75    19.1
15   12.9      74    22.2
16   12.9      85    33.8
17   13.3      86    27.4
18   13.7      71    25.7
19   13.8      64    24.9
20   14.0      78    34.5
21   14.2      80    31.7
22   14.5      74    36.3
23   16.0      72    38.3
24   16.3      77    42.6
25   17.3      81    55.4
26   17.5      82    55.7
27   17.9      80    58.3
28   18.0      80    51.5
29   18.0      80    51.0
30   20.6      87    77.0

In [36]:
mtcars = sm.datasets.get_rdataset('mtcars')['data']
mtcars

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3   
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3   
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   1   0     3   
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3   
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5   
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5   
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

                     carb  
Mazda RX4               4  
Mazda RX4 Wag           4  
Datsun 710              1  
Hornet 4 Drive          1  
Hornet Sportabout       2  
Valiant                 1  
Duster 360              4  
Merc 240D               2  
Merc 230                2  
Merc 280                4  
Merc 280C               4  
Merc 450SE              3  
Merc 450SL              3  
Merc 450SLC             3  
Cadillac Fleetwood      4  
Lincoln Continental     4  
Chrysler Imperial       4  
Fiat 128                1  
Honda Civic             2  
Toyota Corolla          1  
Toyota Corona           1  
Dodge Challenger        2  
AMC Javelin             2  
Camaro Z28              4  
Pontiac Firebird        2  
Fiat X1-9               1  
Porsche 914-2           2  
Lotus Europa            2  
Ford Pantera L          4  
Ferrari Dino            6  
Maserati Bora           8  
Volvo 142E              2