In [1]:
import numpy as np

In [2]:
x = np.array([1.0, 2.0, 3.0])

In [3]:
x

array([1., 2., 3.])

In [4]:
type(x)

numpy.ndarray

In [5]:
y = x/3

In [6]:
y

array([0.33333333, 0.66666667, 1.        ])

In [7]:
x = np.array([1.0, 2.0, 3.0])

In [8]:
y = np.array([2.0, 4.0, 6.0])

In [9]:
x+y

array([3., 6., 9.])

In [10]:
x-y

array([-1., -2., -3.])

In [11]:
x*y

array([ 2.,  8., 18.])

In [12]:
x/y

array([0.5, 0.5, 0.5])