In [1]:
import numpy as np

In [2]:
A = np.array([[5,7],[9,11]])

In [3]:
A

array([[ 5,  7],
       [ 9, 11]])

In [4]:
A[0]

array([5, 7])

In [5]:
A[1]

array([ 9, 11])

In [6]:
A[0,0]

5

In [7]:
A[1,0]

9

In [8]:
B = np.array([[3,0],[0,6]])

In [9]:
A+B

array([[ 8,  7],
       [ 9, 17]])

In [10]:
A*B

array([[15,  0],
       [ 0, 66]])

In [11]:
'**********'

'**********'

In [14]:
A = np.array([[1,2],[3,4]])

In [15]:
B = np.array([10, 20])

In [16]:
C = 10

In [17]:
A*B

array([[10, 40],
       [30, 80]])

In [18]:
A*C

array([[10, 20],
       [30, 40]])