In [1]:
xv <- c(1, 10, 20, 50, 100)

In [2]:
is.vector(xv)

[1] TRUE

In [3]:
xv[2]

[1] 10

In [4]:
xv[c(1,3)]

[1]  1 20

In [5]:
x<-c(1,2,'a',TRUE)

In [6]:
x

[1] "1"    "2"    "a"    "TRUE"

In [7]:
# 문자열로 형변환됨(나머지들이 문자열로 바뀔 수 있으니)

In [8]:
is.numeric(x[1])

[1] FALSE

In [9]:
xx <- c(1,2,TRUE)

In [10]:
xx

[1] 1 2 1

In [11]:
# 숫자랑 불린값만 있으면 숫자로 변환가능(불린이 숫자로 변환할 수 있으니)

In [12]:
length(xv)

[1] 5

In [16]:
xm <- matrix(1:9, nrow=3, dimnames=list(c('r1','r2','r3'), c('c1','c2','c3')))
xm

c1 c2 c3
r1 1  4  7 
r2 2  5  8 
r3 3  6  9

In [17]:
xm <- matrix(1:9, nrow=3, byrow=T, dimnames=list(c('r1','r2','r3'), c('c1','c2','c3')))
xm

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

In [18]:
xm[1,2]

[1] 2

In [19]:
xm[1,]

c1 c2 c3 
 1  2  3

In [20]:
xm[1, 2:3]

c2 c3 
 2  3

In [21]:
length(xm)

[1] 9

In [22]:
dim(xm)

[1] 3 3

In [24]:
xv

[1]   1  10  20  50 100

In [25]:
xv[2]<- -5
xv

[1]   1  -5  20  50 100

In [27]:
xm

c1 c2 c3
r1 1  2  3 
r2 4  5  6 
r3 7  8  9

In [29]:
xm[1,2] <- 10
xm

c1 c2 c3
r1 1  10 3 
r2 4   5 6 
r3 7   8 9

In [31]:
##########
# R의 데이터프레임
##########

In [33]:
xv <- c(1,2,T)
xv

[1] 1 2 1

In [35]:
xv2 <- c(1,2,'a')
xv2

[1] "1" "2" "a"

In [36]:
x <- seq(1,10,2)
x

[1] 1 3 5 7 9

In [37]:
x <- seq(1,10,by=2)
x

[1] 1 3 5 7 9

In [41]:
letters
# 기존 정의되어있는 변수다

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [42]:
y <- letters[1:length(x)]
y

[1] "a" "b" "c" "d" "e"

In [43]:
df <- data.frame(id=x,name=y)
df

id name
1 1  a   
2 3  b   
3 5  c   
4 7  d   
5 9  e

In [44]:
df[1,]

id name
1 1  a

In [45]:
df[,1]

[1] 1 3 5 7 9

In [46]:
df[1,2]

[1] "a"

In [47]:
df$id

[1] 1 3 5 7 9

In [48]:
df[['name']]

[1] "a" "b" "c" "d" "e"

In [52]:
##########
# 행렬, 벡터의 연산
##########

In [53]:
xv <- seq(1, 10, by=2)
xv

[1] 1 3 5 7 9

In [54]:
xv <- c(xv, 11)
xv

[1]  1  3  5  7  9 11

In [55]:
xv[-3]
xv
#실데이터가 지워지는건 아님

[1]  1  3  7  9 11

[1]  1  3  5  7  9 11

In [56]:
xv[-c(1,3,4)]

[1]  3  9 11

In [58]:
xm<-matrix(1:8, nrow=2,byrow=T)
xm

[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8

In [60]:
y1 <- c(9:12)
y1

[1]  9 10 11 12

In [61]:
xm2 <- rbind(xm, y1)
xm2

[,1] [,2] [,3] [,4]
   1     2    3    4  
   5     6    7    8  
y1 9    10   11   12

In [62]:
rbind(y1,xm)

[,1] [,2] [,3] [,4]
y1 9    10   11   12  
   1     2    3    4  
   5     6    7    8

In [65]:
y2 <- c(10,20,30)
y2

[1] 10 20 30

In [66]:
xm3 <- cbind(y2,xm2)
xm3

y2           
   10 1  2  3  4
   20 5  6  7  8
y1 30 9 10 11 12

In [68]:
xm2[-2,]

[,1] [,2] [,3] [,4]
   1     2    3    4  
y1 9    10   11   12

In [70]:
onetwo<-c(1,2)
onetwo

[1] 1 2

In [72]:
xv1<-seq(1,10)
ones<-rep(1,10)
xv1
ones

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1 1 1 1 1 1 1 1 1 1

In [73]:
xv1 + onetwo

[1]  2  4  4  6  6  8  8 10 10 12