In [1]:
import numpy as np

In [2]:
xv = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
xv = np.arange(1,10)
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
xv[4]

5

In [7]:
xv[1:4]

array([2, 3, 4])

In [8]:
len(xv)

9

In [11]:
xm = np.array([[1,2,3],[4,5,6],[7,8,9]])
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
xm = np.arange(1,10)
xm

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
xm = xm.reshape(3,3)
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
xm = np.array(range(1,10)).reshape(3,3)
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
xm.shape

(3, 3)

In [21]:
xm[1,2]

6

In [22]:
xm[:,0]

array([1, 4, 7])

In [23]:
xm[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
xv[3] = 11
xv

array([ 1,  2,  3, 11,  5,  6,  7,  8,  9])

In [26]:
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
xm[0,2] = 11
xm

array([[ 1,  2, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
##########
# list
##########

In [30]:
a = [2,3,'c']
a

[2, 3, 'c']

In [31]:
x = [1,2,'a',a]
x

[1, 2, 'a', [2, 3, 'c']]

In [32]:
x[3]

[2, 3, 'c']

In [33]:
x2 = [[1,2,3],[4,5,6],[7,8,9]]
x2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
x2[0][2]

3

In [35]:
x2[2]

[7, 8, 9]

In [36]:
[row[2] for row in x2]

[3, 6, 9]

In [37]:
##########
# tuple
##########

In [39]:
tpl = (1,2,3)
tpl

(1, 2, 3)

In [40]:
type(tpl)

tuple

In [41]:
tpl[2]

3

In [42]:
tpl[2]=3

TypeError: 'tuple' object does not support item assignment

In [43]:
##########
# dictionary
##########

In [44]:
country_code={'korea':82, 'us':1, 'china':86}
country_code

{'korea': 82, 'us': 1, 'china': 86}

In [45]:
len(country_code)

3

In [46]:
country_code['korea']

82

In [47]:
country_code[1]

KeyError: 1

In [48]:
country_code.keys()

dict_keys(['korea', 'us', 'china'])

In [49]:
country_code.values()

dict_values([82, 1, 86])

In [50]:
country_code.items()

dict_items([('korea', 82), ('us', 1), ('china', 86)])

In [52]:
##########
# 깊은복사
##########

In [53]:
ym = [[1,2,3],[4,5,6],[7,8,9]]
ym

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [59]:
from copy import deepcopy

In [60]:
ym2 = deepcopy(ym)
ym2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
ym[0][0] = 10

In [62]:
ym

[[10, 2, 3], [4, 5, 6], [7, 8, 9]]

In [63]:
ym2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [64]:
# deepcopy가 일어난걸 확인할 수 있다.

In [66]:
import pandas as pd
import numpy as np

In [67]:
d = {'name':['Kim','Lee','Park'],'height':[170,180,175]}

In [69]:
df1 = pd.DataFrame(data=d)
df1

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [70]:
df2 = pd.DataFrame([['Kim',170],['Lee',180],['Park',175]],columns=['name','height'])
df2

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [71]:
df3 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]),columns=['a','b','c'])
df3

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [72]:
df3.describe()

a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [74]:
x = df1['height']
x

0    170
1    180
2    175
Name: height, dtype: int64

In [78]:
y = df1.iloc[0:2]
y
# 0에서 부터 1까지 추출한다.

name  height
0  Kim     170
1  Lee     180

In [79]:
# iloc 은 integer-location의 줄임말이다.
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html
# loc라고 label-location도 있다.

In [81]:
y = df1.iloc[:,]
y

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [82]:
y = df1.iloc[:,0]
y

0     Kim
1     Lee
2    Park
Name: name, dtype: object

In [89]:
y = df1.iloc[:,-1]
y
# 거꾸로 간당

0    170
1    180
2    175
Name: height, dtype: int64

In [90]:
y = df1.iloc[[1,2],0]
y

1     Lee
2    Park
Name: name, dtype: object

In [1]:
import numpy as np

In [2]:
x1 = [1,2,3,4]
x1

[1, 2, 3, 4]

In [3]:
x2 = [5,6,7,8]
x2

[5, 6, 7, 8]

In [4]:
y1 = np.array([1,2,3,4])
y1

array([1, 2, 3, 4])

In [5]:
y2 = np.array([5,6,7,8])
y2

array([5, 6, 7, 8])

In [9]:
x1+[2]

[1, 2, 3, 4, 2]

In [10]:
y1+2

array([3, 4, 5, 6])

In [11]:
x1+x2

[1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
y1+y2

array([ 6,  8, 10, 12])

In [13]:
xrow = np.array([1,2,3])
xrow

array([1, 2, 3])

In [14]:
xcol = np.array([[1],[2],[3]])
xcol

array([[1],
       [2],
       [3]])

In [15]:
xrow.shape

(3,)

In [16]:
xcol.shape

(3, 1)

In [17]:
aa = np.array(range(1,11))
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
bb = np.array(range(1,6))
bb

array([1, 2, 3, 4, 5])

In [20]:
cc = np.array([1,2,1,2,1])
cc

array([1, 2, 1, 2, 1])

In [21]:
bb+cc

array([2, 4, 4, 6, 6])

In [23]:
aa+bb

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [24]:
aa*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [25]:
bb**2

array([ 1,  4,  9, 16, 25])

In [26]:
import numpy as np

In [27]:
a = np.array(range(1,11,2))
a

array([1, 3, 5, 7, 9])

In [28]:
a1 = np.delete(a,2)
a1

array([1, 3, 7, 9])

In [29]:
idx = [0,1,3]
idx

[0, 1, 3]

In [30]:
a2 = np.delete(a,idx)
a2

array([5, 9])

In [31]:
b1 = 11
a3 = np.append(a, b1)
a3

array([ 1,  3,  5,  7,  9, 11])

In [32]:
b2 = 2
a4 = np.insert(a,1,b2)
a4

array([1, 2, 3, 5, 7, 9])

In [33]:
b3 = [1,2,3]
a5 = np.insert(a,2,b3)
a5

array([1, 3, 1, 2, 3, 5, 7, 9])

In [34]:
mx1 = np.array(range(1,10)).reshape(3,3)
mx1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
mx2 = np.append(mx1, np.array([10,20,30]))
mx2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20, 30])

In [36]:
# np.append는 shape를 파괴하고 list로 바꾼다음에 추가한다.

In [52]:
mx2 = np.append(mx1, np.array([10,20,30]).reshape(1,3),axis=0)
mx2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [54]:
mx3 = np.append(mx1, np.array([10,20,30]).reshape(3,1),axis=1)
mx3

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [47]:
mx4 = np.delete(mx1, 0, axis=0)
mx4


array([[4, 5, 6],
       [7, 8, 9]])

In [49]:
mx5 = np.delete(mx1, [0,1], axis=1)
mx5

array([[3],
       [6],
       [9]])

In [50]:
mx6 = np.insert(mx1, 1, np.array([10,20,30]), axis=0)
mx6

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [55]:
mx7 = np.insert(mx1, 1, np.array(range(10,100,10)).reshape(3,3),axis=1)
mx7

array([[ 1, 10, 40, 70,  2,  3],
       [ 4, 20, 50, 80,  5,  6],
       [ 7, 30, 60, 90,  8,  9]])

In [56]:
mtx = np.array([[1,2,3],[4,5,6]])
mtx

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
mtx = np.array([1,2,3,4,5,6]).reshape(2,3)
mtx

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
mx1 = np.array(range(1,7)).reshape(2,3)
mx1

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
mx2 = np.hstack((np.repeat(1,3).reshape(3,1),
                np.repeat(2,3).reshape(3,1)))
mx2

array([[1, 2],
       [1, 2],
       [1, 2]])

In [60]:
mx3 = np.matmul(mx1,mx2)
mx3

array([[ 6, 12],
       [15, 30]])

In [61]:
##########
# 워크북 문제
##########

In [67]:
# 2. 파이썬에서 다음 결과는?
xm = np.array([[1,2,3],[4,5,6],[7,8,9]])
xm.shape

(3, 3)

In [68]:
# 3. 파이썬에서 다음 결과는?
x2 = [[1,2,3],[4,5,6],[7,8,9]]
x2[2]

[7, 8, 9]

In [69]:
# 4. 파이썬에서 다음 결과는?
tpl = (1,2,3)
type(tpl)

tuple

In [70]:
# 6. 파이썬에서 print(df1)의 결과는?
import pandas as pd
import numpy as np
d = {'name':['Kim', 'Lee', 'Park'], 'height':[170,180,175]}
df1 = pd.DataFrame(data=d)
print(df1)

   name  height
0   Kim     170
1   Lee     180
2  Park     175


In [71]:
# 7. 파이썬에서 print(x)의 결과는?
import pandas as pd
import numpy as np
d = {'name':['Kim', 'Lee', 'Park'], 'height':[170,180,175]}
df1 = pd.DataFrame(data=d)
x = df1['height']
x

0    170
1    180
2    175
Name: height, dtype: int64

In [72]:
# 9. 파이썬에서 print(y1+y2)의 수행 결과는?
import numpy as np
x1 = [1,2,3,4]
x2 = [5,6,7,8]
y1 = np.array(x1)
y2 = np.array(y2)
y1 + y2

array([ 6,  8, 10, 12])

In [73]:
# 10. 파이썬에서 두 행렬ㄹ mx1, mx2의 곱을 구하고자 한다. ( ) 안에 들어갈 식은?
import numpy as np
mx1 = np.array(range(1,7)).reshape(2,3)
mx2 = np.array([1,2,1,2,1,2]).reshape(3,2)
#mx3 = ( )
mx3 = np.matmul(mx1,mx2)
mx3

array([[ 6, 12],
       [15, 30]])