In [1]:
import numpy as np

In [2]:
xv = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
xv = np.arange(1,10)
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
xv[4]

5

In [7]:
xv[1:4]

array([2, 3, 4])

In [8]:
len(xv)

9

In [11]:
xm = np.array([[1,2,3],[4,5,6],[7,8,9]])
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
xm = np.arange(1,10)
xm

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
xm = xm.reshape(3,3)
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
xm = np.array(range(1,10)).reshape(3,3)
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
xm.shape

(3, 3)

In [21]:
xm[1,2]

6

In [22]:
xm[:,0]

array([1, 4, 7])

In [23]:
xm[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
xv[3] = 11
xv

array([ 1,  2,  3, 11,  5,  6,  7,  8,  9])

In [26]:
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
xm[0,2] = 11
xm

array([[ 1,  2, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
##########
# list
##########

In [30]:
a = [2,3,'c']
a

[2, 3, 'c']

In [31]:
x = [1,2,'a',a]
x

[1, 2, 'a', [2, 3, 'c']]

In [32]:
x[3]

[2, 3, 'c']

In [33]:
x2 = [[1,2,3],[4,5,6],[7,8,9]]
x2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
x2[0][2]

3

In [35]:
x2[2]

[7, 8, 9]

In [36]:
[row[2] for row in x2]

[3, 6, 9]

In [37]:
##########
# tuple
##########

In [39]:
tpl = (1,2,3)
tpl

(1, 2, 3)

In [40]:
type(tpl)

tuple

In [41]:
tpl[2]

3

In [42]:
tpl[2]=3

TypeError: 'tuple' object does not support item assignment

In [43]:
##########
# dictionary
##########

In [44]:
country_code={'korea':82, 'us':1, 'china':86}
country_code

{'korea': 82, 'us': 1, 'china': 86}

In [45]:
len(country_code)

3

In [46]:
country_code['korea']

82

In [47]:
country_code[1]

KeyError: 1

In [48]:
country_code.keys()

dict_keys(['korea', 'us', 'china'])

In [49]:
country_code.values()

dict_values([82, 1, 86])

In [50]:
country_code.items()

dict_items([('korea', 82), ('us', 1), ('china', 86)])

In [52]:
##########
# 깊은복사
##########

In [53]:
ym = [[1,2,3],[4,5,6],[7,8,9]]
ym

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [59]:
from copy import deepcopy

In [60]:
ym2 = deepcopy(ym)
ym2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
ym[0][0] = 10

In [62]:
ym

[[10, 2, 3], [4, 5, 6], [7, 8, 9]]

In [63]:
ym2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [64]:
# deepcopy가 일어난걸 확인할 수 있다.

In [66]:
import pandas as pd
import numpy as np

In [67]:
d = {'name':['Kim','Lee','Park'],'height':[170,180,175]}

In [69]:
df1 = pd.DataFrame(data=d)
df1

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [70]:
df2 = pd.DataFrame([['Kim',170],['Lee',180],['Park',175]],columns=['name','height'])
df2

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [71]:
df3 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]),columns=['a','b','c'])
df3

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [72]:
df3.describe()

a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [74]:
x = df1['height']
x

0    170
1    180
2    175
Name: height, dtype: int64

In [78]:
y = df1.iloc[0:2]
y
# 0에서 부터 1까지 추출한다.

name  height
0  Kim     170
1  Lee     180

In [79]:
# iloc 은 integer-location의 줄임말이다.
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html
# loc라고 label-location도 있다.

In [81]:
y = df1.iloc[:,]
y

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [82]:
y = df1.iloc[:,0]
y

0     Kim
1     Lee
2    Park
Name: name, dtype: object

In [89]:
y = df1.iloc[:,-1]
y
# 거꾸로 간당

0    170
1    180
2    175
Name: height, dtype: int64

In [90]:
y = df1.iloc[[1,2],0]
y

1     Lee
2    Park
Name: name, dtype: object