In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
s = Series([10,20,30], index=['a','b','c'])
s

a    10
b    20
c    30
dtype: int64

In [3]:
df=DataFrame(s, columns=['A'])
df

A
a  10
b  20
c  30

In [4]:
s.__class__

pandas.core.series.Series

In [5]:
df.__class__

pandas.core.frame.DataFrame

In [6]:
s.to_numpy()

array([10, 20, 30])

In [7]:
df.to_numpy()

array([[10],
       [20],
       [30]])

In [9]:
s.to_numpy().shape

(3,)

In [10]:
df.to_numpy().shape

(3, 1)

In [12]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [13]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [14]:
df.columns

Index(['A'], dtype='object')

In [16]:
d = {'one': Series([1,2],index=['a','b']),
    'two': Series([1,2,3],index=['a','b','c'])}
df=DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  NaN    3

In [18]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [19]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [20]:
df = DataFrame(x)
df

0  1
0  0  1
1  2  3

In [21]:
df.columns=['A','B']
df.index=[11,12]
df

A  B
11  0  1
12  2  3

In [30]:
# 1.4 R 데이터 불러오기
import statsmodels.api as sm

In [27]:
trees = sm.datasets.get_rdataset('trees')['data']
trees

Girth  Height  Volume
0     8.3      70    10.3
1     8.6      65    10.3
2     8.8      63    10.2
3    10.5      72    16.4
4    10.7      81    18.8
5    10.8      83    19.7
6    11.0      66    15.6
7    11.0      75    18.2
8    11.1      80    22.6
9    11.2      75    19.9
10   11.3      79    24.2
11   11.4      76    21.0
12   11.4      76    21.4
13   11.7      69    21.3
14   12.0      75    19.1
15   12.9      74    22.2
16   12.9      85    33.8
17   13.3      86    27.4
18   13.7      71    25.7
19   13.8      64    24.9
20   14.0      78    34.5
21   14.2      80    31.7
22   14.5      74    36.3
23   16.0      72    38.3
24   16.3      77    42.6
25   17.3      81    55.4
26   17.5      82    55.7
27   17.9      80    58.3
28   18.0      80    51.5
29   18.0      80    51.0
30   20.6      87    77.0

In [28]:
mtcars = sm.datasets.get_rdataset('mtcars')['data']
mtcars

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3   
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3   
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   1   0     3   
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3   
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5   
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5   
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

                     carb  
Mazda RX4               4  
Mazda RX4 Wag           4  
Datsun 710              1  
Hornet 4 Drive          1  
Hornet Sportabout       2  
Valiant                 1  
Duster 360              4  
Merc 240D               2  
Merc 230                2  
Merc 280                4  
Merc 280C               4  
Merc 450SE              3  
Merc 450SL              3  
Merc 450SLC             3  
Cadillac Fleetwood      4  
Lincoln Continental     4  
Chrysler Imperial       4  
Fiat 128                1  
Honda Civic             2  
Toyota Corolla          1  
Toyota Corona           1  
Dodge Challenger        2  
AMC Javelin             2  
Camaro Z28              4  
Pontiac Firebird        2  
Fiat X1-9               1  
Porsche 914-2           2  
Lotus Europa            2  
Ford Pantera L          4  
Ferrari Dino            6  
Maserati Bora           8  
Volvo 142E              2

In [29]:
iris = sm.datasets.get_rdataset('iris')['data']
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [31]:
# 1.5 Series 자료의 이용

In [32]:
s1 = Series([1.0,2,3])
s1

0    1.0
1    2.0
2    3.0
dtype: float64

In [33]:
sa = Series([1.0,2,3],index=['a','b','c'])
sa

a    1.0
b    2.0
c    3.0
dtype: float64

In [42]:
sc = Series([0.0,1,2],index=['a','b','d'])
sc

a    0.0
b    1.0
d    2.0
dtype: float64

In [57]:
sn = Series([1, 2, 1, 3, 3, 5, 3, 4])
sn

0    1
1    2
2    1
3    3
4    3
5    5
6    3
7    4
dtype: int64

In [58]:
s1

0    1.0
1    2.0
2    3.0
dtype: float64

In [45]:
s1 - 2

0   -1.0
1    0.0
2    1.0
dtype: float64

In [46]:
sa

a    1.0
b    2.0
c    3.0
dtype: float64

In [47]:
sc

a    0.0
b    1.0
d    2.0
dtype: float64

In [48]:
sac = sa + sc
sac

a    1.0
b    3.0
c    NaN
d    NaN
dtype: float64

In [49]:
sac.isnull()

a    False
b    False
c     True
d     True
dtype: bool

In [50]:
sac.notnull()

a     True
b     True
c    False
d    False
dtype: bool

In [52]:
sac.fillna(-1.0)

a    1.0
b    3.0
c   -1.0
d   -1.0
dtype: float64

In [53]:
sx = sac.dropna()
sx

a    1.0
b    3.0
dtype: float64

In [54]:
sy = sx.append(sc[:2])
sy

a    1.0
b    3.0
a    0.0
b    1.0
dtype: float64

In [55]:
sy.drop('a')

b    3.0
b    1.0
dtype: float64

In [59]:
sn.head()

0    1
1    2
2    1
3    3
4    3
dtype: int64

In [60]:
sn.describe()

count    8.00000
mean     2.75000
std      1.38873
min      1.00000
25%      1.75000
50%      3.00000
75%      3.25000
max      5.00000
dtype: float64

In [61]:
list(sn.unique())

[1, 2, 3, 5, 4]

In [62]:
sn.nunique()

5

In [63]:
sn.replace([1,2],0)

0    0
1    0
2    0
3    3
4    3
5    5
6    3
7    4
dtype: int64

In [64]:
# 1.6 DataFrame 자료의 이용

In [66]:
tree4 = trees[0:4].copy()
tree4

Girth  Height  Volume
0    8.3      70    10.3
1    8.6      65    10.3
2    8.8      63    10.2
3   10.5      72    16.4

In [68]:
tree4.index = ['B','E','C','A']
tree4
# index는 굳이 말하면 행을 의미함

Girth  Height  Volume
B    8.3      70    10.3
E    8.6      65    10.3
C    8.8      63    10.2
A   10.5      72    16.4

In [70]:
tree4[tree4>10]

Girth  Height  Volume
B    NaN      70    10.3
E    NaN      65    10.3
C    NaN      63    10.2
A   10.5      72    16.4

In [71]:
tree4[tree4.Height>65]

Girth  Height  Volume
B    8.3      70    10.3
A   10.5      72    16.4

In [72]:
tree4['E':'A']

Girth  Height  Volume
E    8.6      65    10.3
C    8.8      63    10.2
A   10.5      72    16.4

In [78]:
tree4[['Girth','Height']]

Girth  Height
B    8.3      70
E    8.6      65
C    8.8      63
A   10.5      72

In [79]:
tree4.iloc[[0,2],[0,1]]

Girth  Height
B    8.3      70
C    8.8      63

In [80]:
tree4.iloc[:2,[0,2]]

Girth  Volume
B    8.3    10.3
E    8.6    10.3

In [81]:
tree4.iloc[:2,0:1]

Girth
B    8.3
E    8.6

In [82]:
tree4.loc['E':'C']

Girth  Height  Volume
E    8.6      65    10.3
C    8.8      63    10.2

In [83]:
tree4.loc[['E','C'],['Girth', 'Height']]

Girth  Height
E    8.6      65
C    8.8      63

In [85]:
tree4.loc['E':'C', 'Girth':'Volume']

Girth  Height  Volume
E    8.6      65    10.3
C    8.8      63    10.2

In [86]:
tree4.T

B     E     C     A
Girth    8.3   8.6   8.8  10.5
Height  70.0  65.0  63.0  72.0
Volume  10.3  10.3  10.2  16.4

In [87]:
tree4.sort_index()

Girth  Height  Volume
A   10.5      72    16.4
B    8.3      70    10.3
C    8.8      63    10.2
E    8.6      65    10.3

In [88]:
tree4.sort_values('Height')

Girth  Height  Volume
C    8.8      63    10.2
E    8.6      65    10.3
B    8.3      70    10.3
A   10.5      72    16.4

In [91]:
print(tree4.mean())
print()
print(tree4.mean(1))

Girth      9.05
Height    67.50
Volume    11.80
dtype: float64

B    29.533333
E    27.966667
C    27.333333
A    32.966667
dtype: float64


In [92]:
tree4.cumsum()

Girth  Height  Volume
B    8.3      70    10.3
E   16.9     135    20.6
C   25.7     198    30.8
A   36.2     270    47.2

In [93]:
tree4.apply(np.cumsum)

Girth  Height  Volume
B    8.3      70    10.3
E   16.9     135    20.6
C   25.7     198    30.8
A   36.2     270    47.2

In [94]:
tree4.apply(lambda x: x.max())

Girth     10.5
Height    72.0
Volume    16.4
dtype: float64

In [95]:
mtx = mtcars[['mpg', 'cyl', 'hp', 'gear']].copy()
mtx

mpg  cyl   hp  gear
Mazda RX4            21.0    6  110     4
Mazda RX4 Wag        21.0    6  110     4
Datsun 710           22.8    4   93     4
Hornet 4 Drive       21.4    6  110     3
Hornet Sportabout    18.7    8  175     3
Valiant              18.1    6  105     3
Duster 360           14.3    8  245     3
Merc 240D            24.4    4   62     4
Merc 230             22.8    4   95     4
Merc 280             19.2    6  123     4
Merc 280C            17.8    6  123     4
Merc 450SE           16.4    8  180     3
Merc 450SL           17.3    8  180     3
Merc 450SLC          15.2    8  180     3
Cadillac Fleetwood   10.4    8  205     3
Lincoln Continental  10.4    8  215     3
Chrysler Imperial    14.7    8  230     3
Fiat 128             32.4    4   66     4
Honda Civic          30.4    4   52     4
Toyota Corolla       33.9    4   65     4
Toyota Corona        21.5    4   97     3
Dodge Challenger     15.5    8  150     3
AMC Javelin          15.2    8  150     3
Camaro Z28           13.3    8  245     3
Pontiac Firebird     19.2    8  175     3
Fiat X1-9            27.3    4   66     4
Porsche 914-2        26.0    4   91     5
Lotus Europa         30.4    4  113     5
Ford Pantera L       15.8    8  264     5
Ferrari Dino         19.7    6  175     5
Maserati Bora        15.0    8  335     5
Volvo 142E           21.4    4  109     4

In [96]:
mtx.head()

mpg  cyl   hp  gear
Mazda RX4          21.0    6  110     4
Mazda RX4 Wag      21.0    6  110     4
Datsun 710         22.8    4   93     4
Hornet 4 Drive     21.4    6  110     3
Hornet Sportabout  18.7    8  175     3

In [98]:
pd.crosstab(mtx.cyl,mtx.gear)

gear   3  4  5
cyl           
4      1  8  2
6      2  4  1
8     12  0  2

In [99]:
mtn = mtx.groupby(by=['cyl','gear']).mean()
mtn

mpg          hp
cyl gear                    
4   3     21.500   97.000000
    4     26.925   76.000000
    5     28.200  102.000000
6   3     19.750  107.500000
    4     19.750  116.500000
    5     19.700  175.000000
8   3     15.050  194.166667
    5     15.400  299.500000

In [107]:
mtn['mpg'].unstack(0)

cyl        4      6      8
gear                      
3     21.500  19.75  15.05
4     26.925  19.75    NaN
5     28.200  19.70  15.40

In [105]:
mi = mtn.index
lvs0 = mi.levels[0]
print(lvs0)
cds0 = mi.codes[0]
print(cds0)
lvx0 = lvs0[cds0]
print(lvx0)

Int64Index([4, 6, 8], dtype='int64', name='cyl')
[0 0 0 1 1 1 2 2]
Int64Index([4, 4, 4, 6, 6, 6, 8, 8], dtype='int64', name='cyl')


In [117]:
mi = mtn.index
lvs1 = mi.levels[1]
print(lvs1)
cds1 = mi.codes[1]
print(cds1)
lvx1 = lvs1[cds1]
print(lvx1)

Int64Index([3, 4, 5], dtype='int64', name='gear')
[0 1 2 0 1 2 0 2]
Int64Index([3, 4, 5, 3, 4, 5, 3, 5], dtype='int64', name='gear')


In [121]:
mpgx = mtn['mpg'].to_numpy()
print(mpgx)
print()
d = {mi.names[0]: lvx0, mi.names[1]:lvx1, 'mpg':mpgx}
print(d)
print()
mpga = DataFrame(d)
print(mpga)

[21.5   26.925 28.2   19.75  19.75  19.7   15.05  15.4  ]

{'cyl': Int64Index([4, 4, 4, 6, 6, 6, 8, 8], dtype='int64', name='cyl'), 'gear': Int64Index([3, 4, 5, 3, 4, 5, 3, 5], dtype='int64', name='gear'), 'mpg': array([21.5  , 26.925, 28.2  , 19.75 , 19.75 , 19.7  , 15.05 , 15.4  ])}

   cyl  gear     mpg
0    4     3  21.500
1    4     4  26.925
2    4     5  28.200
3    6     3  19.750
4    6     4  19.750
5    6     5  19.700
6    8     3  15.050
7    8     5  15.400


In [122]:
mpga.pivot(index='gear', columns='cyl', values='mpg')

cyl        4      6      8
gear                      
3     21.500  19.75  15.05
4     26.925  19.75    NaN
5     28.200  19.70  15.40

In [1]:
##########
# 워크북
##########

In [2]:
# 1. Python에서 Series를 이용하여 일차원 배열 자료를 생성하였다. 객체 df를 numpy의 열벡터로 바꾸고자 할 때 ( ) 안에 들어갈 메소드는?

In [3]:
import pandas as pd
import numpy as np

In [4]:
s = pd.Series([10,20,30], index=['a','b','c'])
df = pd.DataFrame(s, columns=['A'])
numdf = df.to_numpy()

In [5]:
numdf

array([[10],
       [20],
       [30]])

In [6]:
# 2. 다음 파이썬 명령에서 df.iloc[1]의 값음?

In [7]:
s = pd.Series([10, 20, 30], index=['a','b','c'])
df = pd.DataFrame(s, columns=['A'])
df.iloc[1]

A    20
Name: b, dtype: int64

In [8]:
# 3. R에서 제공하는 iris 데이터를 파이썬에서 가져와서 DataFrame으로 저장하고자 한다. (ㄱ)에 들어갈 명령은?

In [9]:
import statsmodels.api as sm

In [10]:
iris = sm.datasets.get_rdataset('iris')['data']

In [11]:
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
# 4. 3번에서 iris 데이터프레임의 처음 5개의 케이스를 출력하고자 한다. (ㄴ)에 들어갈명령은 ?

In [13]:
import statsmodels.api as sm

In [14]:
iris = sm.datasets.get_rdataset('iris')['data']

In [15]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [16]:
# 5. 파이썬에서 dataframe의 iloc를 이용하여 결과를 출력하고자 한다. (ㄷ)에 들어갈 명령은?

In [17]:
import statsmodels.api as sm

In [18]:
iris = sm.datasets.get_rdataset('iris')['data']

In [19]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [20]:
iris.iloc[0:3,0:2]

Sepal.Length  Sepal.Width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2